[package]
name = "simple-icons-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
reqwest = { version = "0.12.22", features = ["json"] }
serde_json = "1.0.141"
tokio = { version = "1.47.0", features = ["rt-multi-thread", "macros"] }
